import type { Metadata } from "next";
import "@/app/ui/globals.css";
import { interFont } from "@/app/ui/font";
import { Header } from "@/components/ui/Header/Header";
import { Footer } from "@/components/ui/Footer/Footer";
import StoreProvider from "../components/providers/StoreProvider";
import { Suspense } from "react";
import Loading from "@/app/loading";
import { getUser } from "@/app/actions";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await getUser();
	return (
		<html lang="en">
			<StoreProvider user={user}>
				<body className={`${interFont.className} bg-gray-100`} suppressHydrationWarning={true}>
					<Header/>
						<main className="max-w-screen-xl mx-4 xl:m-auto pt-[60px]">{children}</main>
					<Footer />
				</body>
			</StoreProvider>
		</html>
	);
}
